project:
  type: book
  output-dir: docs
  resources:
    - images/
book:
  title: ""
  chapters:
    - index.qmd
    #- test.qmd
    - WhatsNew.qmd
    - SiteHistory.qmd
    - ClimateChange.qmd
    - Hydrology.qmd
    - CompositionDynamics.qmd
    - BiomassProductivity.qmd
    - Decomp.qmd
    - SoilBiology.qmd
    - Biogeochemistry.qmd
    - AtmosphericInputs.qmd
    - AcidDepositionEffects.qmd
    - MineralWeathering.qmd
    - Roots.qmd
    - Nitrogen.qmd
    - Phosphorus.qmd
    - StreamEcosystems.qmd
    - PhysiologyPhenology.qmd
    - ForestManagement.qmd
    - Beech.qmd
    - Birds.qmd
    - Understory.qmd
    - Scaling.qmd

  sidebar:
    style: docked
    collapse-level: 2
  search: false  

format:
  html:
    title-block: false
    css: styles.css
    toc: true
    toc-title: "Chapter Sections"
    include-before-body: includes/banner.html
#  pdf:
#    documentclass: scrreprt # Example PDF specific option    
    
#from: markdown+raw_html