<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.6.42">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>12&nbsp; Roots and Mycorrhizae</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
</style>


<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<link href="./Nitrogen.html" rel="next">
<link href="./MineralWeathering.html" rel="prev">
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-html/quarto.js"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting-2f5df379a58b258e96c21c0638c20c03.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap-821b353f9d95b26937205047da05f2b0.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>


<link rel="stylesheet" href="styles.css">
</head>

<body class="nav-sidebar docked">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" role="button" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="./Roots.html"><span class="chapter-number">12</span>&nbsp; <span class="chapter-title">Roots and Mycorrhizae</span></a></li></ol></nav>
        <a class="flex-grow-1" role="navigation" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
        </a>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation docked overflow-auto">
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Introduction</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./WhatsNew.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">What’s New</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./SiteHistory.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">Site, History, and Research Approaches</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./ClimateChange.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">Climate Change</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Hydrology.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">Hydrology</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./CompositionDynamics.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">Forest Composition and Dynamics</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./BiomassProductivity.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">Forest Biomass and Primary Productivity</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Decomp.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">Decomposition and Soil Carbon Sequestration</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./SoilBiology.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">7</span>&nbsp; <span class="chapter-title">Soil Biology in the Forested Ecosystem</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Biogeochemistry.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">8</span>&nbsp; <span class="chapter-title">Biogeochemistry: Element behavior and Interactions</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./AtmosphericInputs.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">9</span>&nbsp; <span class="chapter-title">format: html</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./AcidDepositionEffects.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">10</span>&nbsp; <span class="chapter-title">Ecosystem Effects of Acidic Deposition</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./MineralWeathering.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">11</span>&nbsp; <span class="chapter-title">Mineral Weathering</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Roots.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text"><span class="chapter-number">12</span>&nbsp; <span class="chapter-title">Roots and Mycorrhizae</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Nitrogen.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">13</span>&nbsp; <span class="chapter-title">Nitrogen</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Phosphorus.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">14</span>&nbsp; <span class="chapter-title">Phosphorus</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./StreamEcosystems.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">15</span>&nbsp; <span class="chapter-title">Stream Ecosystems in the Hubbard Brook Experimental Forest</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./PhysiologyPhenology.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">16</span>&nbsp; <span class="chapter-title">Forest Physiology and Phenology</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./ForestManagement.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">17</span>&nbsp; <span class="chapter-title">Forest Management and Ecosystem Dynamics</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Beech.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">18</span>&nbsp; <span class="chapter-title">Trouble with Beech</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Birds.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">19</span>&nbsp; <span class="chapter-title">All About Birds</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Understory.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">20</span>&nbsp; <span class="chapter-title">Understory Vegetation</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Scaling.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">21</span>&nbsp; <span class="chapter-title">Scaling Up: Gradients, Models and Remote Sensing</span></span></a>
  </div>
</li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Chapter Sections</h2>
   
  <ul>
  <li><a href="#introduction" id="toc-introduction" class="nav-link active" data-scroll-target="#introduction"><span class="header-section-number">12.1</span> Introduction</a></li>
  <li><a href="#root-biomass" id="toc-root-biomass" class="nav-link" data-scroll-target="#root-biomass"><span class="header-section-number">12.2</span> Root Biomass</a></li>
  <li><a href="#root-classification" id="toc-root-classification" class="nav-link" data-scroll-target="#root-classification"><span class="header-section-number">12.3</span> Root Classification</a></li>
  <li><a href="#root-function" id="toc-root-function" class="nav-link" data-scroll-target="#root-function"><span class="header-section-number">12.4</span> Root Function</a></li>
  <li><a href="#root-production" id="toc-root-production" class="nav-link" data-scroll-target="#root-production"><span class="header-section-number">12.5</span> Root Production</a></li>
  <li><a href="#root-longevity" id="toc-root-longevity" class="nav-link" data-scroll-target="#root-longevity"><span class="header-section-number">12.6</span> Root Longevity</a></li>
  <li><a href="#mycorrhizae" id="toc-mycorrhizae" class="nav-link" data-scroll-target="#mycorrhizae"><span class="header-section-number">12.7</span> Mycorrhizae</a></li>
  <li><a href="#root-activity-and-nutrient-uptake" id="toc-root-activity-and-nutrient-uptake" class="nav-link" data-scroll-target="#root-activity-and-nutrient-uptake"><span class="header-section-number">12.8</span> Root Activity and Nutrient Uptake</a></li>
  <li><a href="#root-response-to-environmental-change" id="toc-root-response-to-environmental-change" class="nav-link" data-scroll-target="#root-response-to-environmental-change"><span class="header-section-number">12.9</span> Root Response to Environmental Change</a></li>
  <li><a href="#questions-for-further-study" id="toc-questions-for-further-study" class="nav-link" data-scroll-target="#questions-for-further-study"><span class="header-section-number">12.10</span> Questions for further study</a></li>
  <li><a href="#access-data" id="toc-access-data" class="nav-link" data-scroll-target="#access-data"><span class="header-section-number">12.11</span> Access Data</a></li>
  <li><a href="#references" id="toc-references" class="nav-link" data-scroll-target="#references"><span class="header-section-number">12.12</span> References</a></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">
<script>
document.addEventListener("DOMContentLoaded", function() {
  const banner = document.createElement("div");
  banner.className = "hb-banner-global";

  banner.innerHTML = `
    <a href="https://hubbardbrook.org" class="hb-banner-link">
      <div class="hb-banner-image">
        <img src="images/banner.jpg" alt="">
        <div class="hb-banner-overlay">
          <div class="hb-banner-title">
            Online Book: A Synthesis of Scientific Research at Hubbard Brook
          </div>
          <div class="hb-banner-subline">
            [return to hubbardbrook.org]
          </div>
        </div>
      </div>
    </a>
  `;

  document.body.prepend(banner);
});
</script>

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title"><span class="chapter-number">12</span>&nbsp; <span class="chapter-title">Roots and Mycorrhizae</span></h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<p>Chapter Editor: Timothy Fahey</p>
<section id="introduction" class="level2" data-number="12.1">
<h2 data-number="12.1" class="anchored" data-anchor-id="introduction"><span class="header-section-number">12.1</span> Introduction</h2>
<p>Roots play a variety of roles in forest ecosystems. Although we usually think of the key role of roots (actually mycorrhizae) in acquiring soil resources, they also serve to anchor the plant and as a place for storing nutrients and carbohydrates. Studying the structure and function of tree root systems requires brute strength or clever techniques because they are difficult to access. At Hubbard Brook considerable attention has been applied to understanding root systems of the trees because they are crucial to forest ecosystem production and biogeochemistry. Here we provide a brief overview of root studies at HB. For a general overview of root structure, anatomy and function we refer readers to treatises on the topics of roots (Eshel and Beeckman 2013) and mycorrhizae (Smith and Read 2010).</p>
</section>
<section id="root-biomass" class="level2" data-number="12.2">
<h2 data-number="12.2" class="anchored" data-anchor-id="root-biomass"><span class="header-section-number">12.2</span> Root Biomass</h2>
<p>Roots typically comprise about 20-25% of total plant biomass in forests; Mokany et al.&nbsp;(2006) summarized global data on root:shoot biomass (R:S) ratios of terrestrial vegetation, indicating a median value of 0.24 for mature temperate broadleaf forests. Based on exceptionally detailed measurements at HB, R:S of the 80-yr-old forest on W6 was estimated at 0.26 (i.e.&nbsp;roots comprised 21% of total plant biomass; Fahey et al.&nbsp;2005a). Total root biomass was estimated independently by two labor-intensive methods at HB: quantitative soil pits (Fahey et al.&nbsp;1988) and allometric equations derived by excavation of root systems of 81 sample trees (Whittaker et al.&nbsp;1974). These estimates differed by 8%. Most of the root biomass in the mature forest is contained in large woody roots (Table 1); for example, fine roots (&lt;2 mm diameter) comprise only about 10% of total root biomass and coarse woody roots (&gt;1 cm diameter) make up 56% (Fahey et al.&nbsp;1988). Table 1. Lateral woody root biomass (&gt;0.6mm) in summer 1983 on watershed 5 at Hubbard Brook. Values in parentheses are standard errors based upon 58 soil pits.</p>
<p><strong>Table 1. Lateral woody root biomass (&gt;0.6 mm) in summer 1983 on watershed 5 at Hubbard Brook. Values in parentheses are standard errors based upon 58 soil pits.</strong></p>
<table class="caption-top table">
<colgroup>
<col style="width: 22%">
<col style="width: 12%">
<col style="width: 12%">
<col style="width: 12%">
<col style="width: 11%">
<col style="width: 8%">
<col style="width: 19%">
</colgroup>
<thead>
<tr class="header">
<th>Soil Depth</th>
<th style="text-align: right;">0.6–1.0</th>
<th style="text-align: right;">1.0–2.5</th>
<th style="text-align: right;">2.5–5.0</th>
<th style="text-align: right;">5.0–10</th>
<th style="text-align: right;">&gt;10</th>
<th>Total</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Forest Floor</td>
<td style="text-align: right;">40</td>
<td style="text-align: right;">63</td>
<td style="text-align: right;">112</td>
<td style="text-align: right;">216</td>
<td style="text-align: right;">745</td>
<td>1187 (303)</td>
</tr>
<tr class="even">
<td>0–10 cm</td>
<td style="text-align: right;">37</td>
<td style="text-align: right;">57</td>
<td style="text-align: right;">69</td>
<td style="text-align: right;">109</td>
<td style="text-align: right;">133</td>
<td>605 (77)</td>
</tr>
<tr class="odd">
<td>10–20 cm</td>
<td style="text-align: right;">26</td>
<td style="text-align: right;">46</td>
<td style="text-align: right;">50</td>
<td style="text-align: right;">69</td>
<td style="text-align: right;">248</td>
<td>440 (118)</td>
</tr>
<tr class="even">
<td>&gt;20 cm</td>
<td style="text-align: right;">31</td>
<td style="text-align: right;">70</td>
<td style="text-align: right;">73</td>
<td style="text-align: right;">88</td>
<td style="text-align: right;">182</td>
<td>444 (87)</td>
</tr>
<tr class="odd">
<td><strong>Total</strong></td>
<td style="text-align: right;">134 (13)</td>
<td style="text-align: right;">235 (25)</td>
<td style="text-align: right;">315 (25)</td>
<td style="text-align: right;">482 (47)</td>
<td style="text-align: right;">1509 (394)</td>
<td>2676 (539)</td>
</tr>
</tbody>
</table>
<p>Tree roots are highly concentrated in the surface soil horizons in most temperate forests (Jackson et al.&nbsp;1996). In northern hardwood forests about 83% of total root biomass is found in the upper 20 cm of soil, and about 40% of fine root biomass is located in the forest floor organic horizons (<a href="#fig-rootdepth" class="quarto-xref">Figure&nbsp;<span>12.1</span></a>). Nevertheless, fine and coarse roots can extend to greater depths (50+ cm) in soil including the C horizon (<a href="#fig-rootdepth" class="quarto-xref">Figure&nbsp;<span>12.1</span></a>), probably depending on soil characteristics such as dense pan layers and perched water tables. In general, the biotic and environmental factors that regulate these gross features of forest root systems are only partially understood. Not surprisingly, R:S ratio increases as shoot biomass decreases, and R:S tends to be greater on sandy soils (Mokany et al.&nbsp;2006) and on poorly-drained soils (Coutts 1983). Probably the relatively high R:S ratio at HB reflects the sandy texture or the low soil fertility.</p>
<div id="fig-rootdepth" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-rootdepth-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="figs/root/rootdepthdistribution.png" class="img-fluid figure-img">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-rootdepth-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;12.1: Depth distribution of fine and small woody roots in northern hardwood stands at Bartlett Experimental Forest. (Yanai et al., 2006).
</figcaption>
</figure>
</div>
<p>Root biomass, size distributions and R:S ratios all change systematically during forest stand development: root biomass and the proportion of large woody roots increase and R:S decreases (Mokany et al.&nbsp;2006) as forests develop. For example, in northern hardwoods at nearby Bartlett Experimental Forest, biomass of roots &lt;2 cm diameter nearly doubled between age 19-27 yr and age 56-69 yr (Yanai et al.&nbsp;2006; <a href="#fig-biomass" class="quarto-xref">Figure&nbsp;<span>12.2</span></a>). Fine root (&lt; 1mm) biomass increased from 300 g/m2 to 410 g/m2 between stand age 40 and 100 yr at HB (Bae et al.&nbsp;2015). Roots in mature forest also extend to greater depths than for young forest (Yanai et al.&nbsp;2006), analogous to increasing canopy heights.</p>
<div id="fig-biomass" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-biomass-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="figs/root/rootbiomass.png" class="img-fluid figure-img">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-biomass-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;12.2: Root biomass in different size classes in northern hardwood stands of different ages at Bartlett Experimental Forest. (Yanai et al., 2006).
</figcaption>
</figure>
</div>
</section>
<section id="root-classification" class="level2" data-number="12.3">
<h2 data-number="12.3" class="anchored" data-anchor-id="root-classification"><span class="header-section-number">12.3</span> Root Classification</h2>
<p>Fine roots are typically defined on the basis of a diameter cut-off (e.g.&nbsp;&lt;1 mm), and most research at HB has employed this definition. From a functional view a more informative approach relies on root order, based on branching pattern: the most distal root segments are classified as the lowest order (1), second-order root segments are formed at the junction of 1st order roots and so on, analogous to the geomorphology of streams (Fitter 1982). The low-order fine roots (order 1-2 or 1-3) are most important in soil resource uptake (water, mineral nutrients) and usually form mycorrhizal symbiosis while the higher orders (order 4-5) are anatomically adapted for resource transport (McCormack et al.&nbsp;2015). However, sampling fine root systems by branching order is difficult and applications of the root order system at Hubbard Brook has been limited; for example, Fahey et al.&nbsp;(2012) observed that order 1-2 fine roots (0.2-0.3 mm diameter) of sugar maple had median longevity of about 220 d whereas for order 4-5 roots (0.6-1.4 mm) median longevity was about 2 years. Additional research utilizing the root order concept is needed to be better characterize fine root function in the HB forest.</p>
<div id="fig-length" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-length-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="figs/root/rootlength.jpg" class="img-fluid figure-img">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-length-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;12.3: Proportion of total root length in different size classes of fine roots in two soil horizons at Hubbard Brook: black = organic, gray = mineral. (Fahey and Hughes 1994).
</figcaption>
</figure>
</div>
</section>
<section id="root-function" class="level2" data-number="12.4">
<h2 data-number="12.4" class="anchored" data-anchor-id="root-function"><span class="header-section-number">12.4</span> Root Function</h2>
<p>From the standpoint of resource uptake functions root length is a more informative measure of root abundance than root biomass; most nutrient uptake models use root length as the basis for uptake calculations (e.g.&nbsp;Yanai 1994). The distribution of the total length of fine roots across diameter classes differs between soil horizons and among the dominant northern hardwood species at HB (Fahey and Hughes 1994; <a href="#fig-length" class="quarto-xref">Figure&nbsp;<span>12.3</span></a>). Roots are smaller in diameter in surface organic horizons than in underlying mineral soil for all three species, and sugar maple roots are smaller than those of beech and yellow birch. A useful index of morphology of fine roots is the specific root length (SRL), defined as the length to dry mass ratio; fine roots with higher SRL would be expected to maximize uptake (length) per energy cost (mass) as shown by Yanai et al.&nbsp;(1995). For a particular root diameter class, SRL is usually higher for roots in forest floor than mineral soil (<a href="#fig-finerootlength" class="quarto-xref">Figure&nbsp;<span>12.4</span></a>); hence, it is not surprising that uptake per unit root mass of a scarce resource like P is much greater in forest floor horizons (see Phosphorus chapter)</p>
<div id="fig-finerootlength" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-finerootlength-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="figs/root/finerootlength.jpg" class="img-fluid figure-img">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-finerootlength-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;12.4: Specific root length of fine roots in different size classes in two soil horizons at Hubbard Brook: black = organic, gray = mineral. (Fahey and Hughes, 1994).
</figcaption>
</figure>
</div>
</section>
<section id="root-production" class="level2" data-number="12.5">
<h2 data-number="12.5" class="anchored" data-anchor-id="root-production"><span class="header-section-number">12.5</span> Root Production</h2>
<p>Root production is difficult to measure because accessing the root system inevitably alters the soil environment and the dynamics of roots. A common approach using root ingrowth cores probably overestimates root production because roots proliferate in the resource-rich, root-free environment of the ingrowth core. Based on this approach fine root production was estimated to be 350 g/m2-yr in the northern hardwood forest at HB, about equally divided between forest floor and mineral soil (Fahey and Hughes 1994). This estimate greatly exceeds the value obtained by measuring fine root biomass (&lt;1 mm) and calculating production from the turnover rate of fine roots. Tierney and Fahey (2002) estimated fine root turnover using minirhizotron (MR) observations in the HB forest at 0.35 yr-1, which they applied to long-term average fine root biomass (&lt;1 mm) of 520 g/m2 to obtain a fine root production estimate of 182 g.m2-yr. The turnover rate estimate of Tierney and Fahey (2002) is lower than other MR estimates for northern hardwood forests (e.g., Hendrick and Pregitzer 1992) because it accounts for the skewed distribution of fine root lifespans (see below). Resolving the differences between ingrowth core and MR estimates of fine root production remains an important challenge. Additional root production is associated with coarse, woody roots (&gt;1 mm) but direct measurements are lacking for HB or indeed for any forests. Fahey et al.&nbsp;(2005a) estimated woody root production for the HB forest to be 76 g/m2-yr based on the assumption that they turn over at the same rate as analogous aboveground biomass (twigs, branches). Thus, woody root production appears to be less than half as large as fine root production, but more refined approaches are needed to confirm these estimates.</p>
<p>Together with aboveground measurements, these estimates provide a basis for calculating the ratio of belowground to total forest production for HB (i.e.&nbsp;BNPP:NPP). The resulting value for the ca. 90-yr-old northern hardwood forest (in the late 1990s) is about 0.3, slightly higher than the average value of 0.26 for temperate deciduous forests (Tierney and Fahey 2007). Higher values of BNPP:NPP are observed in grasslands (0.52) and evergreen boreal forests (0.40).</p>
<p>Also, note that the ratio of root:shoot biomass (0.26) is considerably lower than the ratio of BNPP:ANPP (0.45), reflecting the higher proportion of tissues with relatively rapid turnover in root systems.</p>
<div id="fig-mortality" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-mortality-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="figs/root/rootgrowthmortality.gif" class="img-fluid figure-img">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-mortality-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;12.5: Fine root growth and mortality in reference and treated (snow removal to induce soil freezing) plots over two growing seasons at Hubbard Brook. (Tierney et al., 2001).
</figcaption>
</figure>
</div>
<p>In the cold temperate HB environment seasonal variation in root growth is strongly linked to soil temperature. Observations using MR indicate that root growth commences soon after soils warm following melting of the snowpack in April (Tierney et al.&nbsp;2001; <a href="#fig-mortality" class="quarto-xref">Figure&nbsp;<span>12.5</span></a>), but growth rates remain low until soil temperatures warm in late May and June, coincident with leaf growth. This differs from some warm temperate deciduous forests where root growth declines during leaf expansion, possibly because of competing C demand (Teskey and Hinckley 1981; Joslin et al.&nbsp;2001). In forests where soils dry out during late summer, root growth peaks early in the growing season (Hendrick and Pregitzer 1997; Joslin et al.&nbsp;2001) whereas in the normally moist HB environment root growth remains high in late summer and early fall, closely tracking temperature (<a href="#fig-season" class="quarto-xref">Figure&nbsp;<span>12.6</span></a>).</p>
<div id="fig-season" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-season-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="figs/root/seasonalroot.gif" class="img-fluid figure-img">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-season-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;12.6: Seasonal variation in fine root production depends primarily on temperature at Hubbard Brook. (Tierney at al., 2003).
</figcaption>
</figure>
</div>
</section>
<section id="root-longevity" class="level2" data-number="12.6">
<h2 data-number="12.6" class="anchored" data-anchor-id="root-longevity"><span class="header-section-number">12.6</span> Root Longevity</h2>
<div id="fig-survivor" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-survivor-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="figs/root/rootsurvivorship.jpg" class="img-fluid figure-img">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-survivor-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;12.7: Survivorship curve for fine roots in hardwood forest at Hubbard Brook, based on minirhizotron observations. (Tierney and Fahey, 2002).
</figcaption>
</figure>
</div>
<p>Unlike leaves, fine roots do not appear to undergo programmed senescence with the formation of an abscission layer. Rather, fine root mortality is a continuous process, perhaps responding to local depletion of soil nutrient availability. At HB root mortality roughly tracks root growth and, surprisingly, high overwinter mortality is not normally observed (<a href="#fig-mortality" class="quarto-xref">Figure&nbsp;<span>12.5</span></a>) although severe soil freezing has been shown to damage roots of northern hardwood trees at HB (Cleavitt et al.&nbsp;2008; Tierney et al.&nbsp;2001; Comerford et al.&nbsp;2013; <a href="#fig-mortality" class="quarto-xref">Figure&nbsp;<span>12.5</span></a>). The role of soil invertebrates and fungal pathogens in fine root mortality has received limited attention and deserves further study.</p>
<p>Extensive observations using MR at HB provide a basis for quantifying the survivorship of fine roots in the northern hardwood forest (<a href="#fig-survivor" class="quarto-xref">Figure&nbsp;<span>12.7</span></a>). In general, mortality hazard is initially high but gradually declines for roots surviving past the first few months. Although the median lifespan of fine roots is about 1.5 yr, a substantial fraction (ca. 20%) may live over three years. This strong skewing of the survivorship curve helps to explain an apparent disagreement in the literature on fine roots: Gaudinski et al.&nbsp;(2001) estimated fine root lifespan in eastern deciduous forest using a bomb 14C approach at 3-18 years, whereas other approaches, including MR at HBEF have indicated much shorter lifespans, &lt; 3 yr.</p>
</section>
<section id="mycorrhizae" class="level2" data-number="12.7">
<h2 data-number="12.7" class="anchored" data-anchor-id="mycorrhizae"><span class="header-section-number">12.7</span> Mycorrhizae</h2>
<p>Few of the fine roots in the forest are simply plant tissues; most are actually a mycorrhizal symbiosis. The northern hardwood forest at HB consists of a mixture of tree species that exhibit the two most common types of mycorrhizae: arbuscular mycorrhizae (AM: maples, cherry, ash) and ectomycorrhizae (EM: birches, beech, conifers). These two types of mycorrhizae differ markedly in terms of morphology, physiology and the taxonomy of the fungal partner (Smith and Read 2010). Exactly how these contrasting mycorrhizal types interact within the northern hardwood forest is an intriguing question. For example, AM are well known to enhance plant uptake of P (Bolan 1991) and EM fungal communities are highly sensitive to N supply (Lilleskov et al.&nbsp;2002). Phillips et al.&nbsp;(2013) proposed that these different mycorrhizal types regulate the nutrient economy of forest ecosystems through different couplings among the C-N-P cycles. The sensitivity of mycorrhizal associations to ongoing global environmental change (Treseder 2004) is an important topic deserving attention at HB.</p>
<div id="fig-respiration" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-respiration-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="figs/root/rootrespiration.png" class="img-fluid figure-img">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-respiration-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;12.8: Root respiration rate as a function of soil temperature at Hubbard Brook. Circles denote forest floor and squares denote mineral soil roots. (Fahey et al., 2005b).
</figcaption>
</figure>
</div>
</section>
<section id="root-activity-and-nutrient-uptake" class="level2" data-number="12.8">
<h2 data-number="12.8" class="anchored" data-anchor-id="root-activity-and-nutrient-uptake"><span class="header-section-number">12.8</span> Root Activity and Nutrient Uptake</h2>
<div id="fig-nuptake" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-nuptake-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="figs/root/rootNuptake.png" class="img-fluid figure-img">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-nuptake-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;12.9: Nitrogen uptake by roots of sugar maple as a function of solution N concentration measured on intact and excised roots. (Socci and Templer, 2011).
</figcaption>
</figure>
</div>
<p>Physiological activity of roots is particularly difficult to measure in situ in forests because of sensitivity to disruption of root-soil interactions. Measurements on detached fine roots at HB indicate that respiration increases with soil temperature, following an exponential relationship with a Q10 value of about 3 (Fahey et al.&nbsp;2005b; <a href="#fig-respiration" class="quarto-xref">Figure&nbsp;<span>12.8</span></a>); thus, root respiration is highly sensitive to climate warming. Although soil moisture also affects root respiration it is difficult to separate drought effects from confounding temperature effects (Davidson et al.&nbsp;1998). The current consensus suggests that only severe drought conditions reduce root respiration (Burton et al.&nbsp;1998; Fahey et al.&nbsp;2005b) but more study is needed.</p>
<p>Two general approaches to measurement of nutrient uptake by roots of forest trees have been applied at HB (Socci and Templer 2011). In the in situ depletion method, roots remain connected to the tree whereas uptake of isotopically-labeled nutrients (e.g.&nbsp;15N) is measured on excised roots. The former method generally yields higher uptake estimates (<a href="#fig-nuptake" class="quarto-xref">Figure&nbsp;<span>12.9</span></a>) that are more in line with mass-balance calculations. Campbell et al.&nbsp;(2014) applied the in situ approach in a snow removal experiment at HB and demonstrated that severe soil freezing reduced root N uptake (<a href="#fig-freeze" class="quarto-xref">Figure&nbsp;<span>12.10</span></a>), supporting the interpretation that increased nitrate leaching from northern hardwood forest soils following soil freezing is driven primarily by reduced root N uptake.</p>
<p>A considerable proportion of the C allocated belowground by forest trees is transported to the soil adjacent to the roots, known as rhizosphere C flux (RCF). The C fuels microbial activity including extra-matrical mycorrhizal fungal hyphae, facilitating acquisition of mineral nutrients. Phillips and Fahey (2005) measured RCF of saplings of sugar maple and yellow birch at HB using an isotope labeling approach and extrapolated that 7-12% of tree C assimilation was diverted to RCF in the HB forest. This RCF results in higher microbial biomass, enzymatic activity and organic matter mineralization in rhizosphere soil than in bulk soil, so-called rhizosphere effects. Experimental fertilization studies at HB also indicate that RCF and rhizosphere effects may be modulated by trees in response to changes in nutrient availability (<a href="#fig-rhizosphere" class="quarto-xref">Figure&nbsp;<span>12.11</span></a>; Phillips and Fahey 2007, 2008).</p>
<div id="fig-freeze" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-freeze-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="figs/root/rootfreezing.jpg" class="img-fluid figure-img">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-freeze-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;12.10: Effect of snow removal to induce soil freezing on N uptake by sugar maple roots. (Socci and Templer, 2011).
</figcaption>
</figure>
</div>
</section>
<section id="root-response-to-environmental-change" class="level2" data-number="12.9">
<h2 data-number="12.9" class="anchored" data-anchor-id="root-response-to-environmental-change"><span class="header-section-number">12.9</span> Root Response to Environmental Change</h2>
<div id="fig-rhizosphere" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-rhizosphere-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="figs/root/rhizosphere.gif" class="img-fluid figure-img">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-rhizosphere-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;12.11: Rhizosphere effects on carbon mineralization: % difference between rhizosphere and bulk soil in fertilized (black) and reference (white) plots. (Phillips and Fahey 2007, 2008).
</figcaption>
</figure>
</div>
<p>Human-accelerated environmental changes (climate, pollution, land-use) can be expected to cause substantial alteration of root dynamics of forest ecosystems (Norby and Jackson 2000). Indeed, depletion of base cations at HB during the 20th century was a probable cause of increased fine root biomass in the northern hardwood forest; i.e.&nbsp;experimental restoration of soil calcium resulted in a 30% decline in fine root biomass in WS1 (<a href="#fig-massrat" class="quarto-xref">Figure&nbsp;<span>12.12</span></a>; Fahey et al.&nbsp;2016). Consequently, lower C inputs to forest floor horizons via root turnover and RCF also may have contributed to the decline in forest floor organic matter in WS1. Other important root responses to environmental changes can be expected. In particular, because both root growth and respiration are closely tied to soil temperature (<a href="#fig-season" class="quarto-xref">Figure&nbsp;<span>12.6</span></a>; <a href="#fig-respiration" class="quarto-xref">Figure&nbsp;<span>12.8</span></a>; Atkin et al.&nbsp;2000), we can anticipate changes in response to global warming during the 21st century. For example, the duration of root growth will probably increase; together with higher respiration rates this will result in increased CO2 flux from root systems. More difficult to predict are the possible effects of declining soil N availability resulting from reduced anthropogenic N inputs (see Nitrogen Cycling chapter) and changing P availability associated with soil pH increases due to reduced acid deposition. Moreover, factors controlling fine root turnover are not well understood for HB or any forest ecosystems. Conceptual and methodological advances are needed to inform predictions of root system responses to global change.</p>
<div id="fig-massrat" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-massrat-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="figs/root/rootmassratio.png" class="img-fluid figure-img">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-massrat-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;12.12: Mass ratio of fine root to foliage at three elevations in reference (A) and calcium treated (B) watersheds before (1998) and 14 years after (2013) treatment at Hubbard Brook. Note the large decline in root:shoot ratio after treatment in mid and high elevation zones. (Fahey et al., 2016).
</figcaption>
</figure>
</div>
<p>A better basis for predicting the response of root production to variation in soil nutrient availability has been provided by observations of the MELNHE study of forest ecosystem co-limitation. We hypothesized that increased soil nutrient availability would cause a decrease in tree investment in root nutrient uptake, the so-called “plant functional equilibrium theory” (Thornley 1991). Surprisingly, we have observed just the opposite: significant increases in fine root production in response to long-term addition of N (in mature forest stands; Shan et al.&nbsp;2022, <a href="#fig-ingrowth" class="quarto-xref">Figure&nbsp;<span>12.13</span></a>) and of N + P (in early successional stands; Li et al, in review). Apparently, tree investment in root production can be constrained by nutrient limitation or co-limitation, perhaps reflecting the need for stoichiometrically balanced nutrition.</p>
<p>Fine root growth measured using ingrowth cores in three mature forest stands treated with N and P addition in a full factorial design A. root length and B. root biomass</p>
<div id="fig-ingrowth" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-ingrowth-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="figs/root/ingrowthcores.jpg" class="img-fluid figure-img">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-ingrowth-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;12.13: Fine root growth measured using ingrowth cores in three mature forest stands treated with N and P addition in a full factorial design A. root length and B. root biomass.
</figcaption>
</figure>
</div>
</section>
<section id="questions-for-further-study" class="level2" data-number="12.10">
<h2 data-number="12.10" class="anchored" data-anchor-id="questions-for-further-study"><span class="header-section-number">12.10</span> Questions for further study</h2>
<ul>
<li>What are the principal factors regulating the allocation of C to root systems and the turnover rate of fine roots in the hardwood forest?</li>
<li>Can we resolve the discrepancy in estimates of fine root production between in-growth cores and minirhizotrons?</li>
<li>What are the principal causes of fine root mortality? What is the role invertebrate herbivory and fungal pathogens in root death?</li>
<li>What is the rate of production and turnover of woody roots?</li>
<li>How are root length and biomass distributed among the orders of fine roots of the dominant tree species and different soil horizons?</li>
<li>How do the root systems of trees with arbuscular mycorrhizae and ectomycorrhizae interact in various soil horizons of the northern hardwood forest? How will these interactions respond to environmental changes?</li>
<li>How does nutrient uptake by tree roots respond to environmental changes especially climate and pollutant deposition?</li>
<li>How does rhizosphere carbon flux influence soil nutrient availability and nutrient acquisition by forest trees?</li>
</ul>
</section>
<section id="access-data" class="level2" data-number="12.11">
<h2 data-number="12.11" class="anchored" data-anchor-id="access-data"><span class="header-section-number">12.11</span> Access Data</h2>
<ul>
<li>Fahey, T. 2019. Fine Root Data at the Hubbard Brook Experimental Forest, 1998 and 2013 collections ver 1. Environmental Data Initiative. https://doi.org/10.6073/pasta/c8bd8a99fc7c99de07995c456fa5c601.</li>
</ul>
</section>
<section id="references" class="level2" data-number="12.12">
<h2 data-number="12.12" class="anchored" data-anchor-id="references"><span class="header-section-number">12.12</span> References</h2>
<div class="references">
<p>
Atkin, O. K., Edwards, E. J., &amp; Loveys, B. R. (2000). Response of root respiration to changes in temperature and its relevance to global warming. <em>New Phytologist, 147</em>(1), 141–154. <a href="https://doi.org/10.1046/j.1469-8137.2000.00683.x">https://doi.org/10.1046/j.1469-8137.2000.00683.x</a>
</p>
<p>
Bae, K., Fahey, T. J., Yanai, R. D., &amp; Fisk, M. C. (2015). Soil nitrogen availability affects belowground carbon allocation and soil respiration in northern hardwood forests of New Hampshire. <em>Ecosystems, 18</em>(7), 1179–1191. <a href="https://doi.org/10.1007/s10021-015-9892-7">https://doi.org/10.1007/s10021-015-9892-7</a>
</p>
<p>
Bolan, N. S. (1991). A critical review on the role of mycorrhizal fungi in the uptake of phosphorus by plants. <em>Plant and Soil, 134</em>(2), 189–207. <a href="https://doi.org/10.1007/BF00012037">https://doi.org/10.1007/BF00012037</a>
</p>
<p>
Burton, A. J., Pregitzer, K. S., Zogg, G. P., &amp; Zak, D. R. (1998). Drought reduces root respiration in sugar maple forests. <em>Ecological Applications, 8</em>(3), 771–778. <a href="https://doi.org/10.1890/1051-0761(1998)008[0771:DRRRIS]2.0.CO;2">https://doi.org/10.1890/1051-0761(1998)008[0771:DRRRIS]2.0.CO;2</a>
</p>
<p>
Campbell, J. L., Socci, A. M., &amp; Templer, P. H. (2014). Increased nitrogen leaching following soil freezing is due to decreased root uptake in a northern hardwood forest. <em>Global Change Biology, 20</em>(8), 2663–2673. <a href="https://doi.org/10.1111/gcb.12532">https://doi.org/10.1111/gcb.12532</a>
</p>
<p>
Cleavitt, N. L., Fahey, T. J., Groffman, P. M., Hardy, J. P., Henry, K. S., &amp; Driscoll, C. T. (2008). Effects of soil freezing on fine roots in a northern hardwood forest. <em>Canadian Journal of Forest Research, 38</em>(1), 82–91. <a href="https://doi.org/10.1139/X07-133">https://doi.org/10.1139/X07-133</a>
</p>
<p>
Comerford, D. P., Schaberg, P. G., Templer, P. H., Socci, A. M., Campbell, J. L., &amp; Wallin, K. F. (2013). Influence of experimental snow removal on root and canopy physiology of sugar maple trees. <em>Oecologia, 171</em>(1), 261–269. <a href="https://doi.org/10.1007/s00442-012-2409-3">https://doi.org/10.1007/s00442-012-2409-3</a>
</p>
<p>
Coutts, M. P. (1983). Root architecture and tree stability. <em>Plant and Soil, 71</em>(1), 171–188. <a href="https://doi.org/10.1007/BF02182666">https://doi.org/10.1007/BF02182666</a>
</p>
<p>
Davidson, E. A., Belk, E., &amp; Boone, R. D. (1998). Soil water content and temperature as independent or confounded factors controlling soil respiration. <em>Global Change Biology, 4</em>(2), 217–227. <a href="https://doi.org/10.1046/j.1365-2486.1998.00128.x">https://doi.org/10.1046/j.1365-2486.1998.00128.x</a>
</p>
<p>
Eshel, A., &amp; Beeckman, T. (Eds.). (2013). <em>Plant roots: The hidden half</em>. CRC Press.
</p>
<p>
Fahey, T. J., &amp; Hughes, J. W. (1994). Fine root dynamics in a northern hardwood forest ecosystem. <em>Journal of Ecology, 82</em>, 533–548. <a href="https://doi.org/10.2307/2261262">https://doi.org/10.2307/2261262</a>
</p>
<p>
Fahey, T. J., Heinz, A. K., Battles, J. J., Fisk, M. C., Driscoll, C. T., Blum, J. D., &amp; Johnson, C. E. (2016). Fine root biomass declined following restoration of soil calcium. <em>Canadian Journal of Forest Research, 46</em>(5), 738–744. <a href="https://doi.org/10.1139/cjfr-2015-0390">https://doi.org/10.1139/cjfr-2015-0390</a>
</p>
<p>
Fahey, T. J., Hughes, J. W., Pu, M., &amp; Arthur, M. A. (1988). Root decomposition and nutrient flux following whole-tree harvest. <em>Forest Science, 34</em>(3), 744–768.
</p>
<p>
Fahey, T. J., Jacobs, K. R., &amp; Sherman, R. E. (2012). Fine root turnover estimated by 13C labeling. <em>Canadian Journal of Forest Research, 42</em>(10), 1792–1795. <a href="https://doi.org/10.1139/x2012-111">https://doi.org/10.1139/x2012-111</a>
</p>
<p>
Fahey, T. J., Siccama, T. G., Driscoll, C. T., Likens, G. E., Campbell, J., Johnson, C. E., Battles, J. J., Aber, J. D., Cole, J. J., Fisk, M. C., &amp; Groffman, P. M. (2005a). The biogeochemistry of carbon at Hubbard Brook. <em>Biogeochemistry, 75</em>(1), 109–176. <a href="https://doi.org/10.1007/s10533-004-6321-y">https://doi.org/10.1007/s10533-004-6321-y</a>
</p>
<p>
Fahey, T. J., Tierney, G. L., Fitzhugh, R. D., Wilson, G. F., &amp; Siccama, T. G. (2005b). Soil respiration and soil carbon balance in a northern hardwood forest. <em>Canadian Journal of Forest Research, 35</em>(2), 244–253. <a href="https://doi.org/10.1139/x04-170">https://doi.org/10.1139/x04-170</a>
</p>
<p>
Fitter, A. H. (1982). Morphometric analysis of root systems. <em>Plant, Cell and Environment, 5</em>(4), 313–322. <a href="https://doi.org/10.1111/j.1365-3040.1982.tb00914.x">https://doi.org/10.1111/j.1365-3040.1982.tb00914.x</a>
</p>
<p>
Gaudinski, J. B., Trumbore, S. E., Davidson, E. A., Cook, A. C., Markewitz, D., &amp; Richter, D. D. (2001). The age of fine-root carbon in three forests. <em>Oecologia, 129</em>(3), 420–429. <a href="https://doi.org/10.1007/s004420100752">https://doi.org/10.1007/s004420100752</a>
</p>
<p>
Hendrick, R. L., &amp; Pregitzer, K. S. (1992). The demography of fine roots. <em>Ecology, 73</em>(3), 1094–1104. <a href="https://doi.org/10.2307/1940173">https://doi.org/10.2307/1940173</a>
</p>
<p>
Hendrick, R. L., &amp; Pregitzer, K. S. (1997). Fine root demography and the soil environment. <em>Ecoscience, 4</em>(1), 99–105.
</p>
<p>
Jackson, R. B., Canadell, J., Ehleringer, J. R., Mooney, H. A., Sala, O. E., &amp; Schulze, E. D. (1996). A global analysis of root distributions. <em>Oecologia, 108</em>(3), 389–411. <a href="https://doi.org/10.1007/BF00333714">https://doi.org/10.1007/BF00333714</a>
</p>
<p>
Joslin, J. D., Wolfe, M. H., &amp; Hanson, P. J. (2001). Factors controlling root elongation timing. <em>Plant and Soil, 228</em>(2), 201–212.
</p>
<p>
Lilleskov, E. A., Fahey, T. J., Horton, T. R., &amp; Lovett, G. M. (2002). Ectomycorrhizal fungal community change across nitrogen gradients. <em>Ecology, 83</em>(1), 104–115.
</p>
<p>
McCormack, M. L., et al.&nbsp;(2015). Redefining fine roots improves understanding of belowground processes. <em>New Phytologist, 207</em>(3), 505–518. <a href="https://doi.org/10.1111/nph.13363">https://doi.org/10.1111/nph.13363</a>
</p>
<p>
Mokany, K., Raison, R. J., &amp; Prokushkin, A. S. (2006). Root:shoot ratios in terrestrial biomes. <em>Global Change Biology, 12</em>(1), 84–96. <a href="https://doi.org/10.1111/j.1365-2486.2005.001045.x">https://doi.org/10.1111/j.1365-2486.2005.001045.x</a>
</p>
<p>
Norby, R. J., &amp; Jackson, R. B. (2000). Root dynamics and global change. <em>New Phytologist, 147</em>(1), 3–12. <a href="https://doi.org/10.1046/j.1469-8137.2000.00692.x">https://doi.org/10.1046/j.1469-8137.2000.00692.x</a>
</p>
<p>
Phillips, R. P., &amp; Fahey, T. J. (2005). Rhizosphere carbon flux patterns. <em>Global Change Biology, 11</em>(6), 983–995. <a href="https://doi.org/10.1111/j.1365-2486.2005.00954.x">https://doi.org/10.1111/j.1365-2486.2005.00954.x</a>
</p>
<p>
Phillips, R. P., &amp; Fahey, T. J. (2007). Fertilization effects on fine root biomass. <em>New Phytologist, 176</em>(3), 655–664. <a href="https://doi.org/10.1111/j.1469-8137.2007.02200.x">https://doi.org/10.1111/j.1469-8137.2007.02200.x</a>
</p>
<p>
Phillips, R. P., &amp; Fahey, T. J. (2008). Soil fertility and rhizosphere effects. <em>Soil Science Society of America Journal, 72</em>(2), 453–461.
</p>
<p>
Phillips, R. P., Brzostek, E., &amp; Midgley, M. G. (2013). The mycorrhizal-associated nutrient economy. <em>New Phytologist, 199</em>(1), 41–51. <a href="https://doi.org/10.1111/nph.12221">https://doi.org/10.1111/nph.12221</a>
</p>
<p>
Shan, S., Devens, H., Fahey, T. J., Yanai, R. D., &amp; Fisk, M. C. (2022). Fine root growth response to nitrogen addition. <em>Ecosystems</em>. <a href="https://doi.org/10.1007/s10021-021-00695-3">https://doi.org/10.1007/s10021-021-00695-3</a>
</p>
<p>
Smith, S. E., &amp; Read, D. J. (2010). <em>Mycorrhizal symbiosis</em>. Academic Press.
</p>
<p>
Socci, A. M., &amp; Templer, P. H. (2011). Temporal patterns of nitrogen uptake. <em>Plant Ecology &amp; Diversity, 4</em>(2–3), 141–152.
</p>
<p>
Teskey, R. O., &amp; Hinckley, T. M. (1981). Root growth responses to temperature and water potential. <em>Physiologia Plantarum, 52</em>(3), 363–369.
</p>
<p>
Thornley, J. H. M. (1991). A transport-resistance model of forest growth. <em>Annals of Botany, 68</em>(3), 211–226.
</p>
<p>
Tierney, G. L., &amp; Fahey, T. J. (2002). Fine root turnover comparison methods. <em>Canadian Journal of Forest Research, 32</em>(9), 1692–1697.
</p>
<p>
Tierney, G. L., &amp; Fahey, T. J. (2007). Estimating belowground primary productivity. In T. J. Fahey &amp; A. K. Knapp (Eds.), <em>Principles and standards for measuring primary production</em>. Oxford University Press.
</p>
<p>
Tierney, G. L., Fahey, T. J., Groffman, P. M., Hardy, J. P., Fitzhugh, R. D., &amp; Driscoll, C. T. (2001). Soil freezing alters fine root dynamics. <em>Biogeochemistry, 56</em>(2), 175–190.
</p>
<p>
Tierney, G. L., Fahey, T. J., Groffman, P. M., Hardy, J. P., Fitzhugh, R. D., Driscoll, C. T., &amp; Yavitt, J. B. (2003). Environmental control of fine root dynamics. <em>Global Change Biology, 9</em>(5), 670–679.
</p>
<p>
Treseder, K. K. (2004). Mycorrhizal responses to nitrogen and phosphorus. <em>New Phytologist, 164</em>(2), 347–355.
</p>
<p>
Whittaker, R. H., Bormann, F. H., Likens, G. E., &amp; Siccama, T. G. (1974). Forest biomass and production. <em>Ecological Monographs, 44</em>(2), 233–254.
</p>
<p>
Yanai, R. D. (1994). A steady-state model of nutrient uptake. <em>Soil Science Society of America Journal, 58</em>(5), 1562–1571.
</p>
<p>
Yanai, R. D., Fahey, T. J., &amp; Miller, S. L. (1995). Efficiency of nutrient acquisition. In <em>Resource physiology of conifers</em> (pp.&nbsp;75–103). Academic Press.
</p>
<p>
Yanai, R. D., Park, B. B., &amp; Hamburg, S. P. (2006). Root distribution in northern hardwood stands. <em>Canadian Journal of Forest Research, 36</em>(2), 450–459.
</p>
</div>


</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const onCopySuccess = function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  }
  const getTextToCopy = function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
    text: getTextToCopy
  });
  clipboard.on('success', onCopySuccess);
  if (window.document.getElementById('quarto-embedded-source-code-modal')) {
    const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
      text: getTextToCopy,
      container: window.document.getElementById('quarto-embedded-source-code-modal')
    });
    clipboardModal.on('success', onCopySuccess);
  }
    var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
    var mailtoRegex = new RegExp(/^mailto:/);
      var filterRegex = new RegExp('/' + window.location.host + '/');
    var isInternal = (href) => {
        return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
    }
    // Inspect non-navigation links and adorn them if external
 	var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
    for (var i=0; i<links.length; i++) {
      const link = links[i];
      if (!isInternal(link.href)) {
        // undo the damage that might have been done by quarto-nav.js in the case of
        // links that we want to consider external
        if (link.dataset.originalHref !== undefined) {
          link.href = link.dataset.originalHref;
        }
      }
    }
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      if (note) {
        return note.innerHTML;
      } else {
        return "";
      }
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      if (note.classList.contains("callout")) {
        return note.outerHTML;
      } else {
        return note.innerHTML;
      }
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
<nav class="page-navigation">
  <div class="nav-page nav-page-previous">
      <a href="./MineralWeathering.html" class="pagination-link" aria-label="Mineral Weathering">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text"><span class="chapter-number">11</span>&nbsp; <span class="chapter-title">Mineral Weathering</span></span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="./Nitrogen.html" class="pagination-link" aria-label="Nitrogen">
        <span class="nav-page-text"><span class="chapter-number">13</span>&nbsp; <span class="chapter-title">Nitrogen</span></span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav>
</div> <!-- /content -->




</body></html>